config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
    get "signin" => 'devise/sessions#new'
    delete "signout" => 'devise/sessions#destroy'
    get "signup" => 'devise/registrations#new'
  end

  get 'feed', to: 'feed#show'

  get 'users/:username', to: 'users#show', as: 'user'

  resources :users, only: :show, param: :username do
    member do
      post 'follow', to: "follows#create"
      delete 'unfollow', to: "follows#destroy"
    end
  end

  resources :items do
  member do
    post 'vote', to: "votes#create"
    delete 'unvote', to: "votes#destroy"
    end
  end

  resources :houses
  resources :tweets
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  validates :content, presence: true, length: {maximum: 140}
  validates :user, presence: true

  acts_as_votable
  has_attached_file :image
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action:authenticate_user!, except: [:index, :show]
  # GET /tweets
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  def show
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
    @tweet = current_user.tweets.find(params[:id])
  end

  # POST /tweets
  def create
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to @tweet, notice: 'Tweet was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tweets/1
  def update
    @tweet = current_user.tweets.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Tweet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy
    redirect_to tweets_url, notice: 'Tweet was successfully destroyed.'
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:content, :image)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_for(tweet, html: {multipart:true}) do |f| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class:"form-control" %>
  </div>


  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<div class="container">
  <h1>Editing Tweet</h1>

  <%= render 'form', tweet: @tweet %>

  <%= link_to 'Show', @tweet %> |
  <%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/index.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-4">
      <div class="card card-block">
        <% if user_signed_in? %>
          <h4 class="card-title">User Account</h4>
          <p class="card-text"><%= link_to current_user.username, user_path(current_user.username)  %></p>
        <% else %>
          <p class="card-text"><%= link_to "Sign up now!",  signup_path %></p>
        <%end%>
      </div>
    </div>
    <div class="col-md-8">
      <% if user_signed_in? %>
        <%= link_to 'New Tweet', new_tweet_path %>
      <% end %>
      <ul class="list-group">
          <% @tweets.each do |tweet| %>
          <%= link_to tweet, class:"list-group-item list-group-item-action flex-column align-items-start" do %>
              <h5 class="list-group-item-heading"><%= tweet.user.username %></h5>
                <% if tweet.image? %>
                <center><%= image_tag tweet.image %></center>
                <% end %> 
                <%= tweet.content %>
          <% end %>
        <% end %>
        </ul>
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<div class="container">
  <h1>New Tweet</h1>

  <%= render 'form', tweet: @tweet %>

  <%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/show.html.erb
<div class="container">
  <div class="row">
    <div class="offdet-md-2 col-md-8">
      <div class="card">
        <div class="card-block">
        <h4 class="card-title"><%= link_to @tweet.user.username, user_path(@tweet.user.username) %></h4>
        <% if @tweet.image? %>
         <center><%= image_tag @tweet.image, class:"img-fluid" %></center>
         <% end %> 
          <p class="card-text"><%= @tweet.content %></p>
          <% if @tweet.user == current_user %>
            <%= link_to 'Edit', edit_tweet_path(@tweet) %>
            <%= link_to 'Destroy',@tweet,method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
          <%= link_to 'Back', tweets_path %>
        </div>
      </div>
    </div>
  </div>
</div>