config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
    get "signin" => 'devise/sessions#new'
    delete "signout" => 'devise/sessions#destroy'
    get "signup" => 'devise/registrations#new'
  end

  get 'feed', to: 'feed#show'

  get 'users/:username', to: 'users#show', as: 'user'

  resources :users, only: :show, param: :username do
    member do
      post 'follow', to: "follows#create"
      delete 'unfollow', to: "follows#destroy"
    end
  end

  resources :items do
  member do
    post 'vote', to: "votes#create"
    delete 'unvote', to: "votes#destroy"
    end
  end

  resources :houses
  resources :tweets
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable
  has_many:tweets
  has_many:items

  validates :username, presence: true, uniqueness: true, length: {minimum: 6}
  validates :name, presence: true

  acts_as_followable
  acts_as_follower
  acts_as_voter 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(username: params[:username])
    @tweets = @user.tweets 
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-4">
      <div class="card card-block">
        <h4 class="card-title"><%= @user.username %></h4>
        <p class="card-text"><%= @user.name %></p>
        <% if user_signed_in? %>
          <% if current_user.following?(@user) %>
            <p class="card-text"><%= link_to "Unfollow", unfollow_user_path(@user.username), method: :delete %></p>
            <% else %>
            <p class="card-text"><%= link_to "Follow", follow_user_path(@user.username), method: :post %></p>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-md-8">
      <ul class="list-group">
          <% @tweets.each do |tweet| %>
          <%= link_to tweet, class:"list-group-item list-group-item-action flex-column align-items-start" do %>
              <h5 class="list-group-item-heading"><%= tweet.user.username %></h5>
                <%= tweet.content %>
          <% end %>
        <% end %>
        </ul>
    </div>
  </div>
</div>