config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
    get "signin" => 'devise/sessions#new'
    delete "signout" => 'devise/sessions#destroy'
    get "signup" => 'devise/registrations#new'
  end

  get 'feed', to: 'feed#show'

  get 'users/:username', to: 'users#show', as: 'user'

  resources :users, only: :show, param: :username do
    member do
      post 'follow', to: "follows#create"
      delete 'unfollow', to: "follows#destroy"
    end
  end

  resources :items do
  member do
    post 'vote', to: "votes#create"
    delete 'unvote', to: "votes#destroy"
    end
  end

  resources :houses
  resources :tweets
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  validates :user, presence: true

  acts_as_votable
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
before_action:authenticate_user!, except: [:index, :show]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
  end

  # GET /items/new
  def new
    @item = current_user.items.new
  end

  # GET /items/1/edit
  def edit
    @item = current_user.items.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.new(item_params)
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
      else
      render :new
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    @item = current_user.items.find(params[:id])
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
      else
      render :edit
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = current_user_items.find(params[:id])
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private


    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :url, :text)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class:"form-control" %>
  </div>

<p><strong>OR</strong></p>

  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_area :text, class:"form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="container">
  <h1>Editing Item</h1>

  <%= render 'form', item: @item %>

  <%= link_to 'Show', @item %> |
  <%= link_to 'Back', items_path %>
</div>

app/views/items/index.html.erb
<div class="container">
  <h1>Items</h1>

  <table>
    <thead>
      <tr>
        <th>Votes</th>
        <th>User</th>
        <th>Title</th>
        <th>Url</th>
        <th>Text</th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.votes_for.up.size %></td>
          <td><%= item.user.username %></td>
          <td><%= item.title %></td>
          <td><%= item.url %></td>
          <td><%= item.text %></td>
          <td><%= link_to 'Show', item %></td>
          <% if user_signed_in? %>
            <% if current_user.voted_up_on? item %>
              <td><%= link_to 'Unvote', unvote_item_path(item), method: :delete %></td>
            <% else %>
              <td><%= link_to 'Vote', vote_item_path(item), method: :post %></td>
            <% end %>
          <% end %>
          <% if item.user == current_user %>
          <td><%= link_to 'Edit', edit_item_path(item) %></td>
          <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Item', new_item_path %>
</div>

app/views/items/new.html.erb
<div class="container">
  <h1>New Item</h1>

  <%= render 'form', item: @item %>

  <%= link_to 'Back', items_path %>
</div>

app/views/items/show.html.erb
<div class="container">

  <p>
    <strong>User:</strong>
    <%= @item.user.username %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= @item.title %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= @item.url %>
  </p>

  <% if @item.text? %>
    <p>
      <strong>Text:</strong>
      <%= @item.text %>
    </p>
<% end %>

<% if @item.user == current_user %>
  <%= link_to 'Edit', edit_item_path(@item) %> |
<% end %>
  <%= link_to 'Back', items_path %>
</div>